# -*- coding: utf-8 -*-
# Contenido del deck - Parte 1 (Juan David Pineda, Pyxis) - ICAL26
# Sesión: "Cuando IT frena tu proyecto AV: seguridad que se diseña, no se parcha"

EVENT = {
    "fecha": "Jueves 22 de octubre de 2026 - 16:30 a 18:00",
    "lugar": "World Trade Center - Ciudad de Mexico - InfoComm America Latina 2026",
    "sesión": "Cuando IT frena tu proyecto AV",
    "subtitulo": "Seguridad que se diseña, no se parcha",
}

# Cada slide: kind + campos. El builder decide layout y estilo.
SLIDES = [
  {
    "kind": "cover",
    "title": "Cuando IT frena tu proyecto AV",
    "subtitle": "Seguridad que se diseña, no se parcha",
    "fecha_lugar": "22 de octubre de 2026   ·   WTC, Ciudad de México",
    "presenter1": "Parte 1:  Juan Pineda  ·  Service Delivery Manager / Tech Academy Lead  ·  Pyxis",
    "presenter2": "Parte 2:  Eduardo Travi  ·  Business Development Manager, CTS  ·  AVI SPL",
  },
  {
    "kind": "content",
    "title": "¿Qué vamos a hacer en estos 90 minutos?",
    "diagram": "agenda",
    "bullets": [
      ("Parte 1 - Los conceptos (45 min, Juan David / Pyxis)", 0, True),
      ("Por qué IT frena un proyecto AV, el marco con el que piensan y el ciclo de vida de un ataque.", 1, False),
      ("Con mini demos en vivo sobre una red aislada que trajimos nosotros.", 1, False),
      ("Parte 2 - La prueba de concepto (Eduardo / AVI SPL)", 0, True),
      ("Un caso real con SIP: cómo fugas pequeñas se combinan y terminan en un ataque dirigido.", 1, False),
      ("No necesitas laptop: participas desde tu teléfono, sobre una red WiFi que llevamos nosotros.", 0, True),
      ("Puedes seguir todo sin instalar nada.", 1, False),
      ("Para quien quiera ir más a fondo: un escáner de red opcional en el teléfono.", 1, False),
      ("El kit se descarga después.", 1, False),
    ],
  },
  {
    "kind": "content",
    "title": "Antes de empezar: uso responsable",
    "diagram": "descargo",
  },
  {
    "kind": "statement",
    "big": "Tu proyecto AV está listo.\nEntonces IT lo revisa y lo frena.",
    "photo": "assets/photos/st_frena.jpg",
    "small": "El problema no es tu diseño. Es que la seguridad se pensó al final, no desde el día uno.",
  },
  {
    "kind": "content",
    "title": "Los pecados que IT ve en tu rack",
    "diagram": 'pecados',
    "bullets": [
      ("Interfaces sin autenticación", 0, True),
      ("Paneles web, APIs y puertos de control abiertos a quien pase por la red.", 1, False),
      ("Protocolos legacy y de descubrimiento", 0, True),
      ("mDNS, Telnet, HTTP plano: pensados para la casa, hablando solos en una red corporativa.", 1, False),
      ("Credenciales de fábrica sin cambiar", 0, True),
      ("admin / admin en equipos que cuestan más que el auto de quien los instaló.", 1, False),
    ],
  },
  {
    "kind": "content",
    "title": "Lo que IT ve cuando mira tu equipo AV",
    "diagram": "dosmiradas",
    "bullets": [
      ("Para ti es un códec, un DSP, un controlador.", 0, True),
      ("Para IT es una computadora más, conectada a su red, que ellos no administran.", 1, False),
      ("Tiene sistema operativo, servicios de red, puertos abiertos y, a veces, acceso a internet.", 1, False),
      ("Si se compromete, es una puerta de entrada al resto de la organización.", 1, False),
      ("Por eso no desconfían de ti. Desconfían de un host desconocido en su red.", 0, True),
    ],
  },
  {
    "kind": "content",
    "title": "Las capas de red: OSI y TCP/IP",
    "diagram": "osi",
  },
  {
    "kind": "content",
    "title": "Marco 1: la tríada CIA",
    "diagram": 'cia',
    "bullets": [
      ("Confidencialidad", 0, True),
      ("Que la señal, las credenciales y la configuración no las vea quien no debe. Ej.: streaming sin cifrar.", 1, False),
      ("Integridad", 0, True),
      ("Que nadie altere lo que se emite ni la configuración del equipo. Ej.: firmware sin firmar.", 1, False),
      ("Disponibilidad", 0, True),
      ("Que el sistema esté cuando se lo necesita. Ej.: la sala de juntas del directorio, caída en vivo.", 1, False),
    ],
  },
  {
    "kind": "content",
    "title": "Marco 2: la hexada de Parker",
    "diagram": "parker",
  },
  {
    "kind": "content",
    "title": "Marco 3: NIST CSF 2.0",
    "diagram": 'nist',
    "bullets": [
      ("Gobernar - quien es responsable de la seguridad de este equipo.", 0, True),
      ("Identificar - que dispositivos hay, que hacen, que exponen.", 0, True),
      ("Proteger - segmentar, cifrar, mínimo privilegio, credenciales.", 0, True),
      ("Detectar - logs y monitoreo: saber cuando algo pasa.", 0, True),
      ("Responder - que se hace cuando hay un incidente.", 0, True),
      ("Recuperar - cómo se vuelve a operar. El integrador toca sobre todo Identificar y Proteger.", 0, True),
    ],
  },
  {
    "kind": "content",
    "title": "Marco 4: defensa en profundidad",
    "diagram": 'criterios',
    "bullets": [
      ("Mínimo privilegio - cada equipo y cada usuario solo lo que necesita, nada más.", 0, True),
      ("Segmentación - el AV en su propia red, separado de la corporativa y de invitados.", 0, True),
      ("Cifrado - control y señal protegidos en tránsito, no en texto plano.", 0, True),
      ("Gestión centralizada de credenciales - nada de admin/admin; cuentas administradas y rotadas.", 0, True),
      ("Son los mismos criterios que vamos a ver atacados, paso a paso, en el resto de la sesión.", 0, True),
    ],
  },
  {
    "kind": "statement",
    "big": "Por qué IT es tan restrictivo:\nporque conoce el ciclo de vida de un ataque.",
    "photo": "assets/photos/st_ataque.jpg",
    "small": "No hace falta un atacante sofisticado. Hace falta una cadena de descuidos pequeños. Veamos esa cadena.",
  },
  {
    "kind": "content",
    "title": "Mapa 1: el ciclo de vida de un ataque",
    "diagram": 'killchain',
    "bullets": [
      ("Cyber Kill Chain (Lockheed Martin) - las fases de un ataque, de punta a punta", 0, True),
      ("Reconocimiento -> Acceso inicial -> Movimiento lateral -> Accion sobre el objetivo.", 1, False),
      ("MITRE ATT&CK - el catálogo de tácticas y técnicas reales", 0, True),
      ("Cada fase se descompone en técnicas concretas, observadas en incidentes reales.", 1, False),
      ("Para que nos sirve a nosotros", 0, True),
      ("Nos da un idioma comun con IT: nombramos el riesgo igual que ellos y lo diseñamos para que no ocurra.", 1, False),
    ],
  },
  {
    "kind": "content",
    "title": "Mapa 2: MITRE ATT&CK",
    "diagram": 'mitre',
    "bullets": [
      ("Matriz pública de tácticas (el porqué) y técnicas (el cómo) de un atacante.", 0, True),
      ("Reconnaissance (TA0043) - escaneo de red. Lo veremos con nmap.", 0, True),
      ("Discovery (TA0007) - descubrimiento mDNS. Lo veremos con Wireshark.", 0, True),
      ("Credential / Initial Access - credenciales de fábrica y paneles sin auth.", 0, True),
      ("Lateral Movement (TA0008) - saltar del AV al resto de la red.", 0, True),
      ("Cada demo va etiquetada con su táctica ATT&CK.", 0, True),
    ],
  },
  {
    "kind": "content",
    "title": "Manos a la obra: conéctate al laboratorio",
    "diagram": "lab",
  },
  {
    "kind": "demo",
    "tag": "ATT&CK - Reconnaissance (TA0043)",
    "title": "Demo 1: reconocimiento con nmap",
    "logo": "assets/logos/nmap.png",
    "bullets": [
      ("Desde la red aislada, un escaneo revela cada host, sus puertos y sus servicios.", 0, True),
      ("En segundos aparece el mapa completo: qué hay, qué versión corre, qué está expuesto.", 0, True),
      ("El atacante no necesita entrar todavía. Solo mirar. Y ya sabe por dónde.", 0, True),
      ("Si quieres, lo corres tú también desde tu teléfono, sobre la red del laboratorio.", 0, True),
    ],
    "shot": "salida de nmap sobre la red del laboratorio",
    "mock": "assets/mocks/nmap_mock.png",
  },
  {
    "kind": "demo",
    "tag": "ATT&CK - Discovery (TA0007)",
    "title": "Demo 2: protocolos de casa (mDNS)",
    "logo": "assets/logos/wireshark.png",
    "bullets": [
      ("mDNS, AirPlay y compañía fueron diseñados para la red de tu casa: anuncian todo, sin autenticar.", 0, True),
      ("Con Wireshark vemos a los equipos AV gritando su nombre, modelo y servicios a toda la red.", 0, True),
      ("Es una de las razones principales por las que IT frena un proyecto AV.", 0, True),
    ],
    "shot": "captura de Wireshark con tráfico mDNS del gateway de presentación",
    "mock": "assets/mocks/wireshark_mock.png",
  },
  {
    "kind": "content",
    "title": "Fugas que, sumadas, dan contexto",
    "diagram": 'fugas',
    "bullets": [
      ("Cada equipo revela una fraccion aparentemente inofensiva:", 0, True),
      ("Hostname y modelo -> que marca y que tipo de equipo es.", 1, False),
      ("Nombres de salas -> el organigrama y quien se sienta donde.", 1, False),
      ("Versión de firmware -> que vulnerabilidades conocidas aplican.", 1, False),
      ("Usuarios de la agenda o del directorio -> nombres y correos reales.", 1, False),
      ("Nada de esto es grave por separado. Combinado, es el guion de un ataque dirigido.", 0, True),
    ],
  },
  {
    "kind": "demo",
    "tag": "ATT&CK - Initial Access / Credential Access",
    "title": "Acceso inicial: la puerta ya estaba abierta",
    "bullets": [
      ("Muchos equipos AV se instalan y se dejan con la credencial de fábrica.", 0, True),
      ("admin/admin, o sin contraseña, en el panel web de control.", 0, True),
      ("Desde ahí se lee la configuración, la agenda, los contactos y a veces se controla el equipo.", 0, True),
    ],
    "shot": "panel de administración del equipo con credencial de fábrica",
    "mock": "assets/mocks/admin_mock.png",
  },
  {
    "kind": "statement",
    "big": "El objetivo no era apagar la pantalla.\nEra el correo de phishing que ahora es creíble.",
    "photo": "assets/photos/st_phishing.jpg",
    "small": "Con nombres, cargos, salas y agenda reales, el atacante escribe un correo que el destinatario no duda en abrir. Eso es lo que está en juego.",
  },
  {
    "kind": "content",
    "title": "Lo que dice AVIXA",
    "diagram": "avixa",
  },
  {
    "kind": "content",
    "title": "Qué proponer: seguridad por fase del proyecto",
    "diagram": 'fases',
    "bullets": [
      ("Diseno - segmentación y requisitos de seguridad en el plano, antes de comprar.", 0, True),
      ("Implementacion - cambiar credenciales, apagar servicios que no se usan, cifrar el control.", 0, True),
      ("Entrega - documentar, dejar logs activos y acordar quien actualiza el firmware.", 0, True),
      ("La seguridad se diseña desde el día uno. No es un parche que se agrega al final.", 0, True),
    ],
  },
  {
    "kind": "content",
    "title": "Segmentación: la propuesta que IT quiere escuchar",
    "diagram": 'segmentación',
    "bullets": [
      ("VLAN AV - los dispositivos AV, aislados del resto.", 0, True),
      ("VLAN de control - el plano de gestión, separado de la señal.", 0, True),
      ("Red corporativa - datos de la empresa, sin contacto directo con el AV.", 0, True),
      ("Red de invitados - el teléfono del visitante nunca toca el AV ni lo corporativo.", 0, True),
      ("Reglas explícitas entre segmentos: solo lo necesario pasa. Todo lo demás, bloqueado.", 0, True),
    ],
  },
  {
    "kind": "content",
    "title": "Secure by default: checklist de hardening",
    "diagram": 'hardening',
    "bullets": [
      ("Cambiar toda credencial de fábrica y usar cuentas administradas.", 0, True),
      ("Apagar servicios y protocolos que no se usan (Telnet, mDNS si no hace falta, UPnP).", 0, True),
      ("Actualizar firmware y acordar quién lo mantiene en el tiempo.", 0, True),
      ("Cifrar control y gestión; nada de HTTP plano ni Telnet.", 0, True),
      ("Dejar logs activos y enviarlos a donde IT pueda verlos.", 0, True),
    ],
  },
  {
    "kind": "content",
    "title": "Las preguntas que IT te va a hacer (y cómo responder)",
    "diagram": "preguntas",
    "bullets": [
      ("¿Qué puertos abre este equipo?  Lista documentada de puertos y servicios.", 0, True),
      ("¿En qué red va a estar?  En la VLAN AV, segmentada, con estas reglas.", 0, True),
      ("¿Cómo se autentican y gestionan las credenciales?  Cuentas administradas, sin fábrica.", 0, True),
      ("¿Cómo actualizamos y monitoreamos?  Plan de firmware y logs hacia su SIEM.", 0, True),
      ("Tener esto listo convierte la revisión de IT en un trámite, no en un freno.", 0, True),
    ],
  },
  {
    "kind": "content",
    "title": "Cuando el cliente no tiene políticas formales",
    "diagram": "cliente",
    "bullets": [
      ("Muchos clientes no tienen un área de seguridad madura. Ahí el integrador marca la diferencia.", 0, True),
      ("Lleva tú el mínimo: segmentación, credenciales, cifrado, logs. Como estándar, no como extra.", 0, True),
      ("Documéntalo y hazlo parte de la entrega. Protege al cliente y te protege a ti.", 0, True),
      ("Es un diferencial comercial: eres el integrador que entrega seguro por defecto.", 0, True),
    ],
  },
  {
    "kind": "content",
    "title": "Para llevar: marcos y herramientas",
    "diagram": "referencias",
  },
  {
    "kind": "closing",
    "title": "Llévate el kit",
    "bullets": [
      ("Checklist de hardening para auditar tus proyectos.", 0, True),
      ("El laboratorio en máquina virtual para practicar en casa.", 0, True),
      ("El guion de preguntas de IT, con sus respuestas.", 0, True),
    ],
    "shot": "Kit de descarga",
    "foot": "Juan Pineda  ·  Pyxis      |      Eduardo Travi  ·  AVI SPL",
  },
  {
    "kind": "section",
    "big": "De la teoría a la práctica:\nla prueba de concepto con SIP.",
    "small": "Eduardo Travi, de AVI SPL, continúa con la prueba de concepto sobre telefonía SIP.",
  },
]
